const os = require('os');

console.log(os.setPriority(-10))
console.log(os.freemem())
console.log(os.homedir())
console.log(os.hostname())
console.log(os.platform())
console.log(os.release())
console.log(os.totalmem())
console.log(os.uptime()/60)
console.log(os.type())
console.log(os.endianness())
console.log(os.getPriority())
console.log(os.loadavg())
console.log(os.constants.signals.SIGQUIT)
console.log(os.machine())
console.log(os.networkInterfaces())
console.log(os.tmpdir())
console.log(os.userInfo('buffer'))